language: python

jobs:
  include:
    dist:
    - bionic
    - focal

python:
  - "3.8"
addons:
  apt:
    packages:
      - libgdal-dev

install:
  - pip install pipenv
  - pipenv install

script: python run.py
